---
name: cmpsc-302-spring-2019-lab8
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src/www/:
    index.html:
        --exists
        --fragment "bootstrap.min.css" --count 1 --exact
        --fragment "<head>" --count 1 --exact
        --fragment "<body>" --count 1 --exact
        --fragment "<h1>" --count 1
        --fragment "<div class" --count 1
        --fragment "bootstrapcdn.com" --count 2
        --fragment "TODO" --count 0 --exact
# --> check the technical writing
# mdl is a Markdown linting tool
# proselint checks writing for common mistakes
writing/reflection.md:
    mdl
    proselint
    --paragraphs 6 --exact
    --fragment "```" --count 2
    --words 50
# --> check the submission image exists
images/responsive_submission.png:
    --exists
# --> check the number of commits beyond a threshold
--commits 10
# --> check that the linter executes and produces 0 lines of output
--command "htmlhint src/www/index.html" --executes
--command "htmlhint src/www/index.html" --count 1 --exact
--command "htmlhint src/www/index.html" --fragment "no errors found" --count 1 --exact
